server:
  port: 4643
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smtpserver52
    password: smtp@52server@52
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: akram
application:
  base-url: http://localhost:4200
  from-mail: smtpserver52@gmail.com
  base64-secret: Zjg2ZDA1M2JlYTE0MmQ0ZmNmNzM1ODI2ZTkzNWIxZTFiMGYzM2Y3ODBjMmQwZWM2YmVjNWNkMGFlMDU3YmQ1NGY2OGI1YmMyMjcwMGMzYmVkYjRlNTFjMjk1ZjBhYzFhMDJhZWU1ZmJjMWUwZWEyNzgxNTcyYzVhNzlhNDUxMzU=
  token-validity-in-seconds: 86400 # 30 minutes
  token-validity-in-seconds-for-remember-me: 2592000 # 24 hours
